# Generated by Django 5.0.6 on 2025-01-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
